apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-menu
  labels:
    app: sky-menu

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sky-menu
  template:
    metadata:
      labels:
        app: sky-menu
    spec:
      containers:
        - name: sky-menu
          image: eyopaa/sky-menu:{{ .Values.image.tag }}
          imagePullPolicy: Always
          
          ports:
            - containerPort: 3000
         
          env:
          - name: DB_HOST
            value: db

          - name: DB_PORT
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: DB_PORT

          - name: DB_NAME
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: DB_NAME

          - name: DB_USER
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: DB_USER
    
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: DB_PASSWORD

          - name: JWT_ACCESS_SECRET
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: JWT_ACCESS_SECRET

          - name: JWT_REFRESH_SECRET
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: JWT_REFRESH_SECRET

          - name: CLOUDINARY_NAME
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: CLOUDINARY_NAME
          
          - name: CLOUDINARY_API_KEY
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: CLOUDINARY_API_KEY

          - name: CLOUDINARY_API_SECRET
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: CLOUDINARY_API_SECRET


          - name: GMAIL_APP_USERNAME
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: GMAIL_APP_USERNAME

          - name: GMAIL_APP_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: pg-secret
                key: GMAIL_APP_PASSWORD

          - name: REDIS_URL
            value: redis

          - name: REDIS_PORT
            value: 6379