apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: sky-menu
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      name: postgres-pod
      app: sky-menu
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: sky-menu
    
    spec: 
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
       
        env: 
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef: 
              name: pg-secret
              key: DB_USER
    
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: pg-secret
              key: DB_PASSWORD