apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sky-menu
  namespace: sky-menu
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sky-menu-api-service
                port:
                  number: 3000
