apiVersion: v1
kind: Secret
metadata: 
  name: pg-secret
type: Opaque
data: 
  
  DB_HOST: bG9jYWxob3N0
  DB_PORT: NTQzMg==
  DB_NAME: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=

